# Generated by Django 3.2.9 on 2021-12-19 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('musicServer', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='song_src',
            field=models.FileField(default='', upload_to='media/songs'),
        ),
    ]
